dist: trusty
sudo: false
group: beta
language: java
addons:
  apt:
    packages:
    - chromium-browser
before_install:
  - dpkg-query -l xvfb chromium-browser
  - which chromium-browser || true
  - which google-chrome || true
install: xvfb-run --auto-servernum bash make.sh
before_script:
  - find . -type f
script: mvn -f webdriver-tests/pom.xml -B verify
